#!/bin/bash

# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)

PROJECT_NAME=$1
CODE_DIR=$2 # = dest = /tmp/sphinxsearch/data.tmp/

BASEDIR=/var/lib/sphinxsearch/data
PID=/var/run/sphinxsearch/searchd.pid
CONFIG=/var/www/vhosts/service-sphinxsearch/private/service-sphinxsearch/etc/sphinxsearch/sphinx.conf

if [ -d "$BASEDIR/index.tmp/" ] 
then
    echo "Directory already exists: removing temporary index directory $BASEDIR/index.tmp ..."
    sudo -u sphinxsearch rm -rf $BASEDIR/index.tmp
fi

echo "creating temporary sphinxsearch data directory $BASEDIR/index.tmp ..."
sudo -u sphinxsearch mkdir -p $BASEDIR/index.tmp

echo "rsync data from temporary deploy folder $CODE_DIR to temporary sphinxsearch folder $BASEDIR/index.tmp/"
sudo -u sphinxsearch rsync -q --update -avz $CODE_DIR $BASEDIR/index.tmp/

if [ -d "$BASEDIR/index.old/" ] 
then
    echo "Directory exists: removing old index directory $BASEDIR/data.old ..."
    sudo -u sphinxsearch rm -rf $BASEDIR/index.old
fi

START=$(date +%s)
if [ -f $PID ]
then
   echo "$PID file exists, assuming that service is running -> stopping sphinx service"
   echo "stopping sphinx service ..."
   START=$(date +%s)
   sudo -u sphinxsearch /etc/init.d/sphinxsearch stop
fi

echo "backup index files to directory $BASEDIR/index.old ..."
sudo -u sphinxsearch mv $BASEDIR/index $BASEDIR/index.old

echo "move new index files from $BASEDIR/data.tmp to $BASEDIR/data ..."
sudo -u sphinxsearch mv $BASEDIR/index.tmp $BASEDIR/index

echo "replace sphinx config file ..."
cp $BASEDIR/index/sphinx.conf /etc/sphinxsearch

echo "starting sphinx service ..."
sudo -u sphinxsearch /etc/init.d/sphinxsearch --conf $CONF start
END=$(date +%s)
DIFF=$(( $END - $START ))
echo "service offline time: $DIFF"

sudo -u sphinxsearch /etc/init.d/sphinxsearch status

exit 0
