#!/bin/bash

# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)

PROJECT_NAME=$1
CODE_DIR=$2 # = dest = /var/cache/deploy/sphinxsearch.data.tmp/

BASEDIR=/var/lib/sphinxsearch/data

if [ -d "$BASEDIR/index.tmp/" ] 
then
    echo "Directory already exists: removing temporary index directory $BASEDIR/index.tmp ..."
    sudo -u sphinxsearch rm -rf $BASEDIR/index.tmp
fi

echo "creating temporary sphinxsearch data directory $BASEDIR/index.tmp ..."
sudo -u sphinxsearch mkdir -p $BASEDIR/index.tmp

echo "rsync data from temporary deploy folder $CODE_DIR to temporary sphinxsearch folder $BASEDIR/index.tmp/"
sudo -u sphinxsearch rsync -q --update -avz $CODE_DIR $BASEDIR/index.tmp/

echo "copy files preserving timestamp ..."
sudo -u sphinxsearch cp $CODE_DIR""sphinx.conf /etc/sphinxsearch/
sudo -u sphinxsearch cp $CODE_DIR""*.py /etc/sphinxsearch/

if [ -d "$BASEDIR/index.old/" ] 
then
    echo "Directory exists: removing old index directory $BASEDIR/data.old ..."
    sudo -u sphinxsearch rm -rf $BASEDIR/index.old
fi

START=$(date +%s)
if pgrep searchd > /dev/null
then
   echo "pgrep searchd returned result, assuming that service is running -> stopping sphinx service"
   echo "stopping sphinx service ..."
   START=$(date +%s)
   sudo -u sphinxsearch /etc/init.d/sphinxsearch stop
fi

echo "backup index files to directory $BASEDIR/index.old ..."
sudo -u sphinxsearch mv $BASEDIR/index $BASEDIR/index.old

echo "move new index files from $BASEDIR/index.tmp to $BASEDIR/index ..."
sudo -u sphinxsearch mv $BASEDIR/index.tmp $BASEDIR/index


DBSUFFIX=$DBSUFFIX_DEFAULT
DBHOST=$DBHOST_T
# TARGET -> integration
if [[ $TARGET == int ]]
then
  DBSUFFIX=$DBSUFFIX_INT;
fi

# TARGET -> production
if [[ $TARGET == prod ]]
then
  DBSUFFIX=$DBSUFFIX_PROD
  DBHOST=$DBHOST_P
fi

# TARGET -> demo
if [[ $TARGET == demo ]]
then
  DBSUFFIX=$DBSUFFIX_DEMO
fi

echo "replace db suffix with $DBSUFFIX (p.e. lubis_3d_dev -> lubis_3d$DBSUFFIX)..."
#                                       (----------$1---------)(---$3---)(-------------$4--------------)   (---$5--)
sudo -u sphinxsearch perl -X -wi -pe 's#(sql_db[ \t]*=[ \t]*\b)(([^\W"]+)(_master|_dev|_prod|_int|_demo)\b|([^\W"]+))#$1$3$5'$DBSUFFIX'#gi' /etc/sphinxsearch/sphinx.conf

echo "replace db host with ${DBHOST} ..."
sudo -u sphinxsearch sed -i "s,pg-sandbox.bgdi.ch,${DBHOST}," /etc/sphinxsearch/sphinx.conf

WAITFORSPHINX=20
COUNTER=1
while pgrep searchd > /dev/null
do
	echo "service still running, waiting for sphinx service to stop, restart-force in $(($WAITFORSPHINX-$COUNTER+1))s ..."
	sleep 1
	COUNTER=$(($COUNTER +1))
	if test $COUNTER -gt $WAITFORSPHINX
	then
		echo "service is not stopping, force stop"
   		START=$(date +%s)
		sudo -u sphinxsearch /etc/init.d/sphinxsearch force-stop
		sleep 1
		break
	fi
done

echo "starting sphinx service ..."
sudo -u sphinxsearch /etc/init.d/sphinxsearch start

END=$(date +%s)
DIFF=$(( $END - $START ))
echo "service offline time: $DIFF"

echo "removing temporary deploy folder on deploy target /var/cache/deploy/sphinxsearch.data.tmp/ ..."
rm -rf $CODE_DIR

sudo -u sphinxsearch /etc/init.d/sphinxsearch status

exit 0
