#!/bin/bash

# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)

PROJECT_NAME=$1
CODE_DIR=$2 # = dest = /var/cache/deploy/sphinxsearch.data.tmp/

BASEDIR=/var/lib/sphinxsearch/data
PID=/var/run/sphinxsearch/searchd.pid

if [ -d "$BASEDIR/index.tmp/" ] 
then
    echo "Directory already exists: removing temporary index directory $BASEDIR/index.tmp ..."
    sudo -u sphinxsearch rm -rf $BASEDIR/index.tmp
fi

echo "creating temporary sphinxsearch data directory $BASEDIR/index.tmp ..."
sudo -u sphinxsearch mkdir -p $BASEDIR/index.tmp

echo "rsync data from temporary deploy folder $CODE_DIR to temporary sphinxsearch folder $BASEDIR/index.tmp/"
sudo -u sphinxsearch rsync -q --update -avz $CODE_DIR $BASEDIR/index.tmp/

echo "removing temporary deploy folder on deploy target /var/cache/deploy/sphinxsearch.data.tmp/ ..."
rm -rf $CODE_DIR

if [ -d "$BASEDIR/index.old/" ] 
then
    echo "Directory exists: removing old index directory $BASEDIR/data.old ..."
    sudo -u sphinxsearch rm -rf $BASEDIR/index.old
fi

START=$(date +%s)
if [ -f $PID ]
then
   echo "$PID file exists, assuming that service is running -> stopping sphinx service"
   echo "stopping sphinx service ..."
   START=$(date +%s)
   sudo -u sphinxsearch /etc/init.d/sphinxsearch stop
fi

echo "backup index files to directory $BASEDIR/index.old ..."
sudo -u sphinxsearch mv $BASEDIR/index $BASEDIR/index.old

echo "move new index files from $BASEDIR/index.tmp to $BASEDIR/data ..."
sudo -u sphinxsearch mv $BASEDIR/index.tmp $BASEDIR/index

echo "replace sphinx config file ..."
cp $BASEDIR/index/sphinx.conf /etc/sphinxsearch

DBHOST=$DBHOST_DEFAULT
# TARGET -> integration
if [[ $TARGET == *ab* ]]
then
  DBHOST=$DBHOST_INT;
fi

# TARGET -> production
if [[ $TARGET == *prod* ]]
then
  DBHOST=$DBHOST_PROD
fi

echo "replace db host with $DBHOST ..."
perl -p -i -e 's/pgcluster0t.bgdi.admin.ch/$DBHOST/' /etc/sphinxsearch/sphinx.conf

WAITFORSPHINX=20
COUNTER=1
while [ -f $PID ]
do
	echo "service still running, waiting for sphinx service to stop, restart-force in $(($WAITFORSPHINX-$COUNTER+1))s ..."
	sleep 1
	COUNTER=$(($COUNTER +1))
	if test $COUNTER -gt $WAITFORSPHINX
	then
		"service is not stopping, force stop"
   		START=$(date +%s)
		sudo -u sphinxsearch /etc/init.d/sphinxsearch force-stop
		sleep 1
		break
	fi
done

echo "starting sphinx service ..."
sudo -u sphinxsearch /etc/init.d/sphinxsearch start

END=$(date +%s)
DIFF=$(( $END - $START ))
echo "service offline time: $DIFF"

echo "removing temporary deploy folder on deploy target /var/cache/deploy/sphinxsearch.data.tmp/ ..."
rm -rf $CODE_DIR

sudo -u sphinxsearch /etc/init.d/sphinxsearch status

exit 0
